module apb_top(PCLK,PRESETn,TRANSFER,READ_WRITE,APB_WRITE_PADDR,APB_WRITE_DATA,APB_READ_PADDR,APB_READ_DATA_OUT);
input wire PCLK,PRESETn,TRANSFER,READ_WRITE;
input wire [8:0]APB_WRITE_PADDR,APB_READ_PADDR;
input wire [7:0]APB_WRITE_DATA;
output wire [7:0]APB_READ_DATA_OUT;

wire PENABLE,PWRITE;
wire PSEL1,PSEL2;
wire [7:0]PW_DATA;
wire [8:0]PADDR;

wire [7:0]PR_DATA1,PR_DATA2;
wire PREADY1,PREADY2;
wire PSLVERR1,PSLVERR2;

wire [7:0]PR_DATA = PSEL1?PR_DATA1:PR_DATA2;
wire PREADY=PSEL1?PREADY1:PREADY2;
wire PSLVERR = PSEL1?PSLVERR1:PSLVERR2;

apb_master master(.PCLK(PCLK),.PRESETn(PRESETn),.PADDR(PADDR),.READ_WRITE(READ_WRITE),.PSEL1(PSEL1),.PSEL2(PSEL2),.TRANSFER(TRANSFER),.PENABLE(PENABLE),.PWRITE(PWRITE),.PW_DATA(PW_DATA),.APB_WRITE_PADDR(APB_WRITE_PADDR),.APB_WRITE_DATA(APB_WRITE_DATA),.APB_READ_PADDR(APB_READ_PADDR),.APB_READ_DATA_OUT(APB_READ_DATA_OUT),.PREADY(PREADY),.PSLVERR(PSLVERR),.PR_DATA(PR_DATA));
apb_slave_1 slave1(.PCLK(PCLK),.PRESETn(PRESETn),.PENABLE(PENABLE),.PWRITE(PWRITE),.PW_DATA(PW_DATA),.PADDR(PADDR[7:0]),.PSEL(PSEL1),.PREADY(PREADY1),.PR_DATA(PR_DATA1),.PSLVERR(PSLVERR1));
apb_slave_2 slave2(.PCLK(PCLK),.PRESETn(PRESETn),.PENABLE(PENABLE),.PWRITE(PWRITE),.PW_DATA(PW_DATA),.PADDR(PADDR[7:0]),.PSEL(PSEL2),.PREADY(PREADY2),.PR_DATA(PR_DATA2),.PSLVERR(PSLVERR2));
endmodule

